ktor:
  development: "$DEBUG:false"
  application:
    modules:
      - com.tickets.ApplicationKt.module
  deployment:
    port: 8080

jwt:
  issuer: "Tickets auth service"
  audience: "main"
  realm: "auth"
  secret: "$JWT_SECRET"

passwords:
  secret: "$PASSWORDS_SECRET"
